kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: magazzino-jenkins
  namespace: nduja
  labels:
    type: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: nduja
  labels:
    type: local
spec:
  storageClassName: magazzino-jenkins
  claimRef:
    name: jenkins-pvc
    namespace: elk
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: nduja
  labels:
    type: local
spec:
  storageClassName: magazzino-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
