kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-space
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: jenkins-space
  claimRef:
    name: jenkins-pv-claim
    namespace: nduja
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: nduja
spec:
  storageClassName: jenkins-space
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
