apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elk-admin
  namespace: elk
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elk-admin
  namespace: elk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elk-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elk-admin
subjects:
- kind: ServiceAccount
  name: elk-admin
  namespace: elk
