apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magazzino-elk
  namespace: elk
  labels:
    type: local
    app: elk
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  namespace: elk
  labels:
    type: local
    app: elk
spec:
  storageClassName: magazzino-elk
  claimRef:
    name: elk-pvc
    namespace: elk
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/elk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
  namespace: elk
  labels:
    type: local
    app: elk
spec:
  storageClassName: magazzino-elk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
